welcome: "This bot will ask you some questions. Please answer them to the best of your ability."
templates:
  - title: "Default Form"
    description: "This is the default form."
    complete: "Thank you for completing the form."
    entries:
    - mode: "text"
      title: "Name"
      correct: "It was a correct name"
      incorrect: "It was an incorrect name"
      description: "Enter your name"
    - mode: "date"
      title: "Date of Birth"
      correct: "It was a correct date of birth"
      incorrect: "It was an incorrect date of birth"
      description: "Enter your date of birth"
    - mode: "oneof"
      title: "Gender"
      correct: "It was a correct answer"
      incorrect: "It was an incorrect answer"
      options:
        - "Male"
        - "Female"
        - "Other"
