welcome: "Hello! This bot can help you to fill out a form, which will be posted to a channel upon approval by channel administrators."
templates:
  - title: "Event announcement"
    description: "This form is used to announce an event."
    complete: "Thank you for completing the form, you will be notified when it is approved or rejected."
    entries:
    - mode: "text"
      title: "Event Name"
      incorrect: "Please, enter a valid event name."
      description: "Enter a short name for the event."
    - mode: "text"
      title: "Date of event"
      incorrect: "Please, enter a valid date."
      description: "Please, enter the date of the event in any format."
    - mode: "text"
      title: "Time of event"
      incorrect: "Please, enter a valid time."
      description: "Please, enter the time of the event in any format."
    - mode: "text"
      title: "Location"
      incorrect: "Please, enter a valid location."
      description: "Please, enter the location of the event."
    - mode: "text"
      title: "Description"
      incorrect: "Please, enter a valid description."
      description: "Please, enter a short description of the event."
    - mode: "oneof"
      title: "Approval of the author"
      incorrect: "Please, select a valid option."
      description: "Do you need to ask the author for approval before visiting the event?"
      options:
        - "Yes"
        - "No"
